server:
  port: 8080

spring:
  neo4j:
    uri: neo4j+s://9484ada8.databases.neo4j.io
    authentication:
      username: neo4j
      password: edARVvmLhFy61hMtkLSYgJE0Y0aTHL9F98YxFVuN5G0
  data:
    neo4j:
      database: neo4j
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


# file
file:
  image:
    base-uri: file:///C:/workplace/backend/java/neo4j_ecommerce_/source/upload/
    folder:
      product: products
      product-banner: banners

# firebase

firebase:
    link-base: https://firebasestorage.googleapis.com/v0/b/ecom-accessed.appspot.com/o/
    bucket: ecom-accessed.appspot.com
