spring:
  neo4j:
    uri: neo4j+s://535b18e9.databases.neo4j.io
    authentication:
      username: neo4j
      password: neo4j

  servlet:
    multipart:
      max-file-size: 10MB


# file
file:
  image:
    base-uri: file:///C:/workplace/backend/java/neo4j_ecommerce_/source/upload/
    folder:
      product: products
      product-banner: banners



