spring:
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: Password1!

  servlet:
    multipart:
      max-file-size: 10MB


# file
file:
  image:
    base-uri: file:///C:/workplace/backend/java/neo4j_ecommerce_/source/upload/
    folder:
      product: products
      product-banner: banners



